export const candidates = [
  {
    id: "c_01",
    name: "Amara Okafor",
    role: "Engineering",
    score: "86.5",
    completedAt: "2026-07-18T09:24:00Z",
    dimensions: [
      { label: "Adaptability", score: "91.0" },
      { label: "Perspective Taking", score: "84.5" },
      { label: "Dependability", score: "83.0" },
      { label: "Intellectual Curiosity", score: "87.5" },
    ],
  },
  {
    id: "c_02",
    name: "Tom Whitfield",
    role: "Engineering",
    score: "71.0",
    completedAt: "2026-07-18T11:02:00Z",
    dimensions: [
      { label: "Adaptability", score: "64.0" },
      { label: "Perspective Taking", score: "78.5" },
      { label: "Dependability", score: "69.0" },
      { label: "Intellectual Curiosity", score: "72.5" },
    ],
  },
  {
    id: "c_03",
    name: "Priya Sharma",
    role: "Product",
    score: "92.0",
    completedAt: "2026-07-17T15:40:00Z",
    dimensions: [
      { label: "Adaptability", score: "95.5" },
      { label: "Perspective Taking", score: "89.0" },
      { label: "Dependability", score: "94.0" },
      { label: "Intellectual Curiosity", score: "89.5" },
    ],
  },
  {
    id: "c_04",
    name: "Daniel Kovacs",
    role: "Sales",
    score: "58.5",
    completedAt: "2026-07-17T10:15:00Z",
    dimensions: [
      { label: "Adaptability", score: "52.0" },
      { label: "Perspective Taking", score: "66.5" },
      { label: "Dependability", score: "61.0" },
      { label: "Intellectual Curiosity", score: "54.5" },
    ],
  },
  {
    id: "c_05",
    name: "Sofia Reyes",
    role: "Product",
    score: "77.5",
    completedAt: "2026-07-16T14:08:00Z",
    dimensions: [
      { label: "Adaptability", score: "80.0" },
      { label: "Perspective Taking", score: "71.5" },
      { label: "Dependability", score: "82.0" },
      { label: "Intellectual Curiosity", score: "76.5" },
    ],
  },
  {
    id: "c_06",
    name: "James Adeyemi",
    role: "Sales",
    score: "83.0",
    completedAt: "2026-07-16T09:55:00Z",
    dimensions: [
      { label: "Adaptability", score: "79.5" },
      { label: "Perspective Taking", score: "88.0" },
      { label: "Dependability", score: "86.5" },
      { label: "Intellectual Curiosity", score: "78.0" },
    ],
  },
  {
    id: "c_07",
    name: "Hannah Lindqvist",
    role: "Engineering",
    score: "68.0",
    completedAt: "2026-07-15T16:30:00Z",
    dimensions: [
      { label: "Adaptability", score: "72.5" },
      { label: "Perspective Taking", score: "60.0" },
      { label: "Dependability", score: "65.5" },
      { label: "Intellectual Curiosity", score: "74.0" },
    ],
  },
  {
    id: "c_08",
    name: "Marcus Chen",
    role: "Product",
    score: "74.5",
    completedAt: "2026-07-15T11:12:00Z",
    dimensions: [
      { label: "Adaptability", score: "77.0" },
      { label: "Perspective Taking", score: "70.5" },
      { label: "Dependability", score: "73.0" },
      { label: "Intellectual Curiosity", score: "77.5" },
    ],
  },
  {
    id: "c_09",
    name: "Elena Petrova",
    role: "Engineering",
    score: "89.5",
    completedAt: "2026-07-14T13:45:00Z",
    dimensions: [
      { label: "Adaptability", score: "92.0" },
      { label: "Perspective Taking", score: "85.5" },
      { label: "Dependability", score: "88.0" },
      { label: "Intellectual Curiosity", score: "92.5" },
    ],
  },
  {
    id: "c_10",
    name: "Oliver Barnes",
    role: "Sales",
    score: "62.5",
    completedAt: "2026-07-14T08:20:00Z",
    dimensions: [
      { label: "Adaptability", score: "58.0" },
      { label: "Perspective Taking", score: "70.0" },
      { label: "Dependability", score: "64.5" },
      { label: "Intellectual Curiosity", score: "57.5" },
    ],
  },
];
